project:
  type: website
  output-dir: docs
website:
  title: "More than an order of words"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Quarto"
        contents:
          - tables.qmd
      - section: "Latex"
        contents:
          - tables.qmd
      - section: "RevealJS"
        contents:
          - RevealJS/revealhome.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    # theme: [cosmo, css/callouts.scss]
    css: css/callouts.css
    include-in-header:
      file: scripts/scripts.js
    