project:
  type: website
  output-dir: docs
website:
  title: "More than an order of words"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - tables.qmd
      - section: "Latex"
        contents:
          - tables.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo


